services:
  app:
    image: 200ms/alpinenet_dev2
    environment:
      - FEATURE=python sudo
      - SUDOERS=true
      - PKGS_ADD=poetry sqlite
      #- TZ=Europe/Warsaw
    volumes:
      - ./pyproject.toml:/app/pyproject.toml:ro
      - ./README.md:/app/README.md:ro
      - ./ecommquery:/app/ecommquery:ro
      - ./tasks:/app/task:ro
      - ./conf:/app/conf:ro
      - ./files/sync.start:/etc/local.d/sync.start:ro
      - ./files/sqliterc:/app/.sqliterc:ro
    healthcheck:
      test: [ "CMD-SHELL", "ps -o comm,args | grep -q -e '^python.*ecommquery'" ]
      interval: 60s
      retries: 3

