services:
  app:
    image: 200ms/alpinenet_dev2
    environment:
      - FEATURE=python sudo
      - SUDOERS=true
      - PKGS_ADD=poetry sqlite
    volumes:
      - ./pyproject.toml:/srv/pyproject.toml:ro
      - ./README.md:/srv/README.md:ro
      - ./ecommquery:/srv/ecommquery:ro
      - ./tasks:/srv/tasks:ro
      - ./confs:/srv/confs:ro
      - ./files/sync.start:/etc/local.d/sync.start:ro
      - ./files/sqliterc:/root/.sqliterc:ro
    healthcheck:
      test: [ "CMD-SHELL", "ps -o comm,args | grep -q -e '^python.*ecommquery'" ]
      interval: 60s
      retries: 3

