services:
  app:
    image: 200ms/alpinenet_dev2
    environment:
      - FEATURE=python sudo
      - SUDOERS=true
      - PKGS_ADD=poetry sqlite
      - APP_ROOT=/home/user
      #- TZ=Europe/Warsaw
    volumes:
      - ./pyproject.toml:/home/user/pyproject.toml:ro
      - ./README.md:/home/user/README.md:ro
      - ./ecommquery:/home/user/ecommquery:ro
      - ./conf:/home/user/conf:ro
      - ./tasks:/home/user/task:ro
      - ./prompts:/home/user/prompts:ro
      - ./files/sync.start:/etc/local.d/sync.start:ro
      - ./files/sqliterc:/home/user/.sqliterc:ro
    working_dir: /home/user
    healthcheck:
      test: [ "CMD-SHELL", "ps -o comm,args | grep -q -e '^python.*ecommquery'" ]
      interval: 60s
      retries: 3

